### ISSUE TITLE
Not returning existing instance in e.g. $("#blah").alpaca()

### ISSUE THREAD

**Issue by dgoldensquared** [gitana/alpaca#162]
It looks like the intent was already for  an `.alpaca()` on an element that was already `.alpaca()`-ed  to return the relevant existing alpaca (field) instance. (common jquery-land plugin convention).  

However it looks like there is a missing `data-` prefix on the attribute name  [in the relevant  `.attr("alpaca-field-id")` call](https://github.com/gitana/alpaca/blob/1.5.0-DEV/src/js/Alpaca.js#L85) used to discover the existing instance, so it apparently always tries to "re-`alpaca()`" the element, to rather unpleasant effect.  I assume the trivial fix would be to use   `.attr("data-alpaca-field-id")`

 (present in 1.5.6 release)

**Comment by francoislg** [comment]
Now that I try to switch to 1.5.0 I have the same problem as you, can't manage to get the Alpaca instance and call methods on it like "setValue" or "getValue", which is pretty annoying.

**Comment by dgoldensquared** [comment]
Yeah, still present in 1.5.6 as far as I can see.  I think there may be a couple of other `.attr("alpaca-field-id")` calls in the code that should now be `.attr("data-alpaca-field-id")`.

**Comment by PiQ99** [comment]
Hey,

I also have to receive current instances of alpaca-forms. Actually I want to call a validate and submit-functionality from a foreign button, that is not included in the form.

 Is there any workaround for this?

**Comment by PiQ99** [comment]
Well a workaround: ATM I follow this more or less ugly way: 
I create these validate/submit buttons in the form (alpaca) and hide them afterwards via jquery-dom-manipulation ($(#BUTTON_ID).hide()). In addition I add an ID to each button and trigger and click-event on these form-buttons via my external buttons in the footer. :-D

**Comment by dgoldensquared** [comment]
> Is there any workaround for this? 

Well, `sed -i 's/"alpaca-field-id"/"data-alpaca-field-id"/g' alpaca.js`, heh,  i.e. locally modify a copy of alpaca to include the relevant `data-` prefix unti it is fixed it in-tree.

**Comment by wmodes** [comment]
Are you kidding? This has been making me crazy. And I am new enough to JS that I just figured it was my own stupidity. I am using alpaca with meteor and figured there was something wrong with the meteor packaged version, not that there was something wrong with alpaca itself. 

I posted about it on stackoverflow here: http://stackoverflow.com/questions/28489798/alpaca-meteor-how-to-address-form-from-within-button-handlers

When I use this code:

    "buttons":{
        "submit":{
            "click": function() {
                console.log(this.getValue()); 
            }
        }
    }

I get an error in the console: `{"message":"undefined is not a function"}`

Is this the same problem? How did you work around it?

**Comment by uzquiano** [comment]
Sticking to the original topic, yes in the 1.5.x code, it looks like the $.alpaca mechanism of retrieving an existing control instance is broken.

This is fixed in the coming 1.5.8 release.  It's refactored in master and you can try it out presently by building yourselves.

The new mechanism:

- $.alpaca() renders a form just as it always did.  If a form is already bound to the underlying DOM element, nothing happens.  This function always returns the jQuery wrapper around the DOM element (as is convention with jQuery).
- $.alpaca("get") retrieves an existing control instance

Alpaca now has support for special functions which can be invoked as shown above.  There are functions for "get", "existing" and "destroy".  Get retrieves the control instance, existing checks whether a control is already bound to the DOM element (true/false) and destroy tears down an existing control instance.

This pattern is what we'll use going forward since it doesn't confuse the nature of the jQuery function and it's return value.  We'll have it in the next release, but feel free to goof on it in head if you want to.

**Comment by lwcolton** [comment]
Is this still broken?   I tried $.alpaca("get") but it returned null.

**Comment by kumudcomms** [comment]
I am using:
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript" src="http://www.alpacajs.org/js/alpaca-latest.min.js"></script>
<link type="text/css" href="http://www.alpacajs.org/css/alpaca-latest.min.css" rel="stylesheet"/>

But still getting:
$("#field1").alpaca' is undefined

Can someone help.
